mime ^text,  label editor = ${VISUAL:-$EDITOR} -- "$@"

mime ^image, has org.kde.krita,     X, flag f = org.kde.krita -- "$@"
ext kra,     has org.kde.krita,     X, flag f = org.kde.krita -- "$@"

mime ^image, has gwenview,  X, flag f = gwenview -- "$@"
mime ^image/svg, has inkscape, X, flag f = inkscape -- "$@"

mime ^image, has gimp,      X, flag f = gimp -- "$@"
ext xcf,                    X, flag f = gimp -- "$@"


# ext png, flag f = gwenview "$@" &
# ext webp, flag f = gwenview "$@" &
# ext jpg, flag f = gwenview "$@" &
